// Code generated by protoc-gen-go.
// source: common.proto
// DO NOT EDIT!

/*
Package specs is a generated protocol buffer package.

It is generated from these files:
	common.proto

It has these top-level messages:
	PageElementDescription
	PageElementIncludes
	RenderArgs
	Empty
	PageRender
	StaticAsset
	Meta
*/
package specs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StaticAsset_Type int32

const (
	StaticAsset_JS  StaticAsset_Type = 0
	StaticAsset_CSS StaticAsset_Type = 1
)

var StaticAsset_Type_name = map[int32]string{
	0: "JS",
	1: "CSS",
}
var StaticAsset_Type_value = map[string]int32{
	"JS":  0,
	"CSS": 1,
}

func (x StaticAsset_Type) String() string {
	return proto.EnumName(StaticAsset_Type_name, int32(x))
}
func (StaticAsset_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 0} }

type PageElementDescription struct {
	Name     string                 `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Version  string                 `protobuf:"bytes,2,opt,name=Version" json:"Version,omitempty"`
	Includes []*PageElementIncludes `protobuf:"bytes,3,rep,name=Includes" json:"Includes,omitempty"`
}

func (m *PageElementDescription) Reset()                    { *m = PageElementDescription{} }
func (m *PageElementDescription) String() string            { return proto.CompactTextString(m) }
func (*PageElementDescription) ProtoMessage()               {}
func (*PageElementDescription) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PageElementDescription) GetIncludes() []*PageElementIncludes {
	if m != nil {
		return m.Includes
	}
	return nil
}

type PageElementIncludes struct {
	Name string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
}

func (m *PageElementIncludes) Reset()                    { *m = PageElementIncludes{} }
func (m *PageElementIncludes) String() string            { return proto.CompactTextString(m) }
func (*PageElementIncludes) ProtoMessage()               {}
func (*PageElementIncludes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type RenderArgs struct {
	Args map[string]string `protobuf:"bytes,1,rep,name=args" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *RenderArgs) Reset()                    { *m = RenderArgs{} }
func (m *RenderArgs) String() string            { return proto.CompactTextString(m) }
func (*RenderArgs) ProtoMessage()               {}
func (*RenderArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RenderArgs) GetArgs() map[string]string {
	if m != nil {
		return m.Args
	}
	return nil
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type PageRender struct {
	Html      string         `protobuf:"bytes,1,opt,name=html" json:"html,omitempty"`
	Assets    []*StaticAsset `protobuf:"bytes,2,rep,name=assets" json:"assets,omitempty"`
	Meta      []*Meta        `protobuf:"bytes,3,rep,name=meta" json:"meta,omitempty"`
	PageTitle string         `protobuf:"bytes,4,opt,name=pageTitle" json:"pageTitle,omitempty"`
}

func (m *PageRender) Reset()                    { *m = PageRender{} }
func (m *PageRender) String() string            { return proto.CompactTextString(m) }
func (*PageRender) ProtoMessage()               {}
func (*PageRender) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PageRender) GetAssets() []*StaticAsset {
	if m != nil {
		return m.Assets
	}
	return nil
}

func (m *PageRender) GetMeta() []*Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type StaticAsset struct {
	Type StaticAsset_Type `protobuf:"varint,1,opt,name=type,enum=specs.StaticAsset_Type" json:"type,omitempty"`
	Path string           `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
}

func (m *StaticAsset) Reset()                    { *m = StaticAsset{} }
func (m *StaticAsset) String() string            { return proto.CompactTextString(m) }
func (*StaticAsset) ProtoMessage()               {}
func (*StaticAsset) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type Meta struct {
	Name      string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Content   string `protobuf:"bytes,2,opt,name=Content" json:"Content,omitempty"`
	HttpEquiv string `protobuf:"bytes,3,opt,name=HttpEquiv" json:"HttpEquiv,omitempty"`
}

func (m *Meta) Reset()                    { *m = Meta{} }
func (m *Meta) String() string            { return proto.CompactTextString(m) }
func (*Meta) ProtoMessage()               {}
func (*Meta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func init() {
	proto.RegisterType((*PageElementDescription)(nil), "specs.PageElementDescription")
	proto.RegisterType((*PageElementIncludes)(nil), "specs.PageElementIncludes")
	proto.RegisterType((*RenderArgs)(nil), "specs.RenderArgs")
	proto.RegisterType((*Empty)(nil), "specs.Empty")
	proto.RegisterType((*PageRender)(nil), "specs.PageRender")
	proto.RegisterType((*StaticAsset)(nil), "specs.StaticAsset")
	proto.RegisterType((*Meta)(nil), "specs.Meta")
	proto.RegisterEnum("specs.StaticAsset_Type", StaticAsset_Type_name, StaticAsset_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for PageElement service

type PageElementClient interface {
	Describe(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PageElementDescription, error)
	Render(ctx context.Context, in *RenderArgs, opts ...grpc.CallOption) (*PageRender, error)
}

type pageElementClient struct {
	cc *grpc.ClientConn
}

func NewPageElementClient(cc *grpc.ClientConn) PageElementClient {
	return &pageElementClient{cc}
}

func (c *pageElementClient) Describe(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PageElementDescription, error) {
	out := new(PageElementDescription)
	err := grpc.Invoke(ctx, "/specs.PageElement/Describe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageElementClient) Render(ctx context.Context, in *RenderArgs, opts ...grpc.CallOption) (*PageRender, error) {
	out := new(PageRender)
	err := grpc.Invoke(ctx, "/specs.PageElement/Render", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PageElement service

type PageElementServer interface {
	Describe(context.Context, *Empty) (*PageElementDescription, error)
	Render(context.Context, *RenderArgs) (*PageRender, error)
}

func RegisterPageElementServer(s *grpc.Server, srv PageElementServer) {
	s.RegisterService(&_PageElement_serviceDesc, srv)
}

func _PageElement_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageElementServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/specs.PageElement/Describe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageElementServer).Describe(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageElement_Render_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageElementServer).Render(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/specs.PageElement/Render",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageElementServer).Render(ctx, req.(*RenderArgs))
	}
	return interceptor(ctx, in, info, handler)
}

var _PageElement_serviceDesc = grpc.ServiceDesc{
	ServiceName: "specs.PageElement",
	HandlerType: (*PageElementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _PageElement_Describe_Handler,
		},
		{
			MethodName: "Render",
			Handler:    _PageElement_Render_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 428 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x52, 0x51, 0x8b, 0xd3, 0x40,
	0x10, 0x36, 0x4d, 0xda, 0x5e, 0xa7, 0x87, 0xf4, 0x46, 0xf1, 0x42, 0x55, 0x3c, 0xf2, 0x74, 0x2a,
	0x44, 0xa8, 0xe0, 0x89, 0x6f, 0xc7, 0x59, 0x50, 0x41, 0x91, 0xed, 0xe1, 0xfb, 0x5e, 0x6e, 0xc8,
	0x05, 0x93, 0xcd, 0x9a, 0x9d, 0x16, 0xf2, 0xe2, 0x1f, 0xf0, 0x4f, 0xcb, 0x6e, 0xb6, 0xbd, 0x40,
	0x7b, 0x2f, 0x61, 0xe6, 0xdb, 0x2f, 0xf3, 0x7d, 0x3b, 0xfb, 0xc1, 0x71, 0x56, 0x57, 0x55, 0xad,
	0x52, 0xdd, 0xd4, 0x5c, 0xe3, 0xd0, 0x68, 0xca, 0x4c, 0xf2, 0x17, 0x9e, 0xfd, 0x94, 0x39, 0x2d,
	0x4b, 0xaa, 0x48, 0xf1, 0x67, 0x32, 0x59, 0x53, 0x68, 0x2e, 0x6a, 0x85, 0x08, 0xd1, 0x0f, 0x59,
	0x51, 0x1c, 0x9c, 0x05, 0xe7, 0x13, 0xe1, 0x6a, 0x8c, 0x61, 0xfc, 0x8b, 0x1a, 0x53, 0xd4, 0x2a,
	0x1e, 0x38, 0x78, 0xdb, 0xe2, 0x07, 0x38, 0xfa, 0xaa, 0xb2, 0x72, 0x7d, 0x4b, 0x26, 0x0e, 0xcf,
	0xc2, 0xf3, 0xe9, 0x62, 0x9e, 0x3a, 0x85, 0xb4, 0x37, 0x7e, 0xcb, 0x10, 0x3b, 0x6e, 0xf2, 0x1a,
	0x9e, 0x1c, 0x20, 0x1c, 0x12, 0x4f, 0x36, 0x00, 0x82, 0xd4, 0x2d, 0x35, 0x97, 0x4d, 0x6e, 0xf0,
	0x1d, 0x44, 0xb2, 0xc9, 0x4d, 0x1c, 0x38, 0xb1, 0xe7, 0x5e, 0xec, 0x9e, 0x90, 0xda, 0xcf, 0x52,
	0x71, 0xd3, 0x0a, 0x47, 0x9c, 0x5f, 0xc0, 0x64, 0x07, 0xe1, 0x0c, 0xc2, 0xdf, 0xd4, 0xfa, 0xf1,
	0xb6, 0xc4, 0xa7, 0x30, 0xdc, 0xc8, 0x72, 0x4d, 0xfe, 0x62, 0x5d, 0xf3, 0x69, 0xf0, 0x31, 0x48,
	0xc6, 0x30, 0x5c, 0x56, 0x9a, 0xdb, 0xe4, 0x5f, 0x00, 0x60, 0xcd, 0x76, 0x22, 0xd6, 0xe3, 0x1d,
	0x57, 0xe5, 0xd6, 0xa3, 0xad, 0xf1, 0x0d, 0x8c, 0xa4, 0x31, 0xc4, 0x26, 0x1e, 0x38, 0x5f, 0xe8,
	0x7d, 0xad, 0x58, 0x72, 0x91, 0x5d, 0xda, 0x23, 0xe1, 0x19, 0xf8, 0x0a, 0xa2, 0x8a, 0x58, 0xfa,
	0x75, 0x4d, 0x3d, 0xf3, 0x3b, 0xb1, 0x14, 0xee, 0x00, 0x5f, 0xc0, 0x44, 0xcb, 0x9c, 0xae, 0x0b,
	0x2e, 0x29, 0x8e, 0x9c, 0xca, 0x3d, 0x90, 0xe4, 0x30, 0xed, 0x4d, 0xc5, 0xb7, 0x10, 0x71, 0xab,
	0xbb, 0x8d, 0x3d, 0x5e, 0x9c, 0xee, 0xeb, 0xa6, 0xd7, 0xad, 0x26, 0xe1, 0x48, 0xd6, 0xba, 0x96,
	0x7c, 0xe7, 0xef, 0xea, 0xea, 0xe4, 0x14, 0x22, 0xcb, 0xc0, 0x11, 0x0c, 0xbe, 0xad, 0x66, 0x8f,
	0x70, 0x0c, 0xe1, 0xd5, 0x6a, 0x35, 0x0b, 0x12, 0x01, 0x91, 0x35, 0xf5, 0x50, 0x20, 0xae, 0x6a,
	0xc5, 0xa4, 0x78, 0x1b, 0x08, 0xdf, 0x5a, 0xf3, 0x5f, 0x98, 0xf5, 0xf2, 0xcf, 0xba, 0xd8, 0xc4,
	0x61, 0x67, 0x7e, 0x07, 0x2c, 0x36, 0x30, 0xed, 0x3d, 0x3b, 0x5e, 0xc0, 0x51, 0x17, 0xbd, 0x1b,
	0xc2, 0x63, 0x6f, 0xdd, 0xed, 0x7c, 0xfe, 0x72, 0x3f, 0x45, 0xfd, 0x90, 0xa6, 0x30, 0xf2, 0xaf,
	0x71, 0xb2, 0x97, 0x80, 0xf9, 0x49, 0xef, 0xdf, 0x0e, 0xbe, 0x19, 0xb9, 0xf0, 0xbf, 0xff, 0x1f,
	0x00, 0x00, 0xff, 0xff, 0xee, 0xee, 0xad, 0xdd, 0x0c, 0x03, 0x00, 0x00,
}
